channels:
  - defaults
  - anaconda
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - jupyterlab
  - ipywidgets
  - matplotlib
  - pytorch
  - pytorch-cuda==11.8
  - torchaudio
  - torchvision
  - memory_profiler
  - openblas-devel
  - cudatoolkit-dev
  - pybind11
  - gcc=9
  - gxx=9
